from __future__ import annotations

try:  # When /test is on sys.path
    from prompts.chat import FIRST_PROMPT, SECOND_PROMPT
except ModuleNotFoundError:  # When repo root is on sys.path
    from test.prompts.chat import FIRST_PROMPT, SECOND_PROMPT

WARMUP_FALLBACK_MESSAGE = "hey there! how are you today?"
BENCHMARK_FALLBACK_MESSAGE = "who was Columbus?"

BENCHMARK_DEFAULT_REQUESTS = 16
BENCHMARK_DEFAULT_CONCURRENCY = 8
BENCHMARK_DEFAULT_TIMEOUT_SEC = 120.0

PERSONALITY_SWITCH_MIN = 1
PERSONALITY_SWITCH_MAX = 10
PERSONALITY_SWITCH_DEFAULT = 4
PERSONALITY_SWITCH_DELAY_SECONDS = 10
PERSONALITY_REPLIES_PER_SWITCH = 2

PERSONA_VARIANTS = [
    ("female", "anna", FIRST_PROMPT),
    ("male", "mark", SECOND_PROMPT),
]

__all__ = [
    "WARMUP_FALLBACK_MESSAGE",
    "BENCHMARK_FALLBACK_MESSAGE",
    "BENCHMARK_DEFAULT_REQUESTS",
    "BENCHMARK_DEFAULT_CONCURRENCY",
    "BENCHMARK_DEFAULT_TIMEOUT_SEC",
    "PERSONALITY_SWITCH_MIN",
    "PERSONALITY_SWITCH_MAX",
    "PERSONALITY_SWITCH_DEFAULT",
    "PERSONALITY_SWITCH_DELAY_SECONDS",
    "PERSONALITY_REPLIES_PER_SWITCH",
    "PERSONA_VARIANTS",
]


