requirement_files = [
    "requirements-dev.txt",
    "requirements-local.txt",
    "requirements-tool.txt",
    "requirements-trt.txt",
    "requirements-vllm.txt",
    "requirements-llmcompressor.txt",
]
