[tool.deptry]
exclude = [
  ".venv",
  ".git",
  "__pycache__",
  ".pytest_cache",
  ".ruff_cache",
  ".mypy_cache",
  "node_modules",
  "docker",
  "linting"
]
ignore_notebooks = true
known_first_party = ["src", "tests"]

[tool.deptry.per_rule_ignores]
DEP001 = ["tensorrt_llm", "flashinfer", "async_timeout", "cuda", "mpi4py"]
DEP002 = [
  "accelerate",
  "compressed-tensors",
  "fla-core",
  "hf_transfer",
  "httpx",
  "loguru",
  "mistral_common",
  "ninja",
  "numpy",
  "nvidia-ml-py",
  "orjson",
  "packaging",
  "protobuf",
  "python-dotenv",
  "pyyaml",
  "rich",
  "safetensors",
  "sentencepiece",
  "setuptools",
  "snac",
  "soundfile",
  "starlette",
  "tqdm",
  "triton",
  "uvicorn",
  "uvloop",
  "wheel"
]
DEP003 = ["anyio", "torchvision"]
DEP004 = ["tomli", "nox"]
