sonar.projectKey=yap-text-inference
sonar.projectName=yap-text-inference
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest.xml
sonar.exclusions=src/scripts/**,tests/support/messages/**,tests/support/prompts/**
sonar.test.inclusions=tests/**/*.py
