"""Audio defaults and analysis constants shared across test utilities."""

DEFAULT_SAMPLE_RATE = 24_000
PCM_CHANNELS = 1
PCM_SAMPLE_WIDTH_BYTES = 2  # 16-bit PCM

LEADING_SILENCE_THRESHOLD_DBFS = -45.0
LEADING_SILENCE_RMS_WINDOW_MS = 10.0
LEADING_SILENCE_SUSTAIN_MS = 30.0
LEADING_SILENCE_NOISE_WINDOW_SEC = 0.4
LEADING_SILENCE_NOISE_PERCENTILE = 20.0
LEADING_SILENCE_THRESHOLD_MULTIPLIER = 4.0
LEADING_SILENCE_TOLERANCE_MS = 25.0
