"""SNAC-specific tuning constants for tests."""

from pathlib import Path

from tests.config.audio import (  # noqa: E402
    LEADING_SILENCE_NOISE_WINDOW_SEC as _AUDIO_NOISE_WINDOW_SEC,
    LEADING_SILENCE_SUSTAIN_MS as _AUDIO_SUSTAIN_MS,
    LEADING_SILENCE_THRESHOLD_MULTIPLIER as _AUDIO_THRESHOLD_MULTIPLIER,
)

DEFAULT_FRAME_HOP_MS = 20.0
DEFAULT_PREPAD_SILENCE_MS = 160.0
LEADING_SILENCE_SUSTAIN_MS = _AUDIO_SUSTAIN_MS
LEADING_SILENCE_WINDOW_SEC = _AUDIO_NOISE_WINDOW_SEC
NOISE_THRESHOLD_MULTIPLIER = _AUDIO_THRESHOLD_MULTIPLIER
MIN_RMS_SAMPLES_FOR_PERCENTILE = 5  # Minimum samples for reliable percentile calculation

_TESTS_DIR = Path(__file__).resolve().parent.parent
SNAC_RESULTS_DIR = _TESTS_DIR / "snac"
