"""Aggregator of configuration modules.

This module re-exports configuration constants from smaller modules:
- deploy: deployment mode and model selection
- gpu: GPU memory and architecture
- engine: inference engine selection
- trt: TensorRT-LLM specific settings
- chat: chat behavior settings
- tool: tool classifier settings
- models: allowlists
- limits: token and concurrency limits
- secrets: secrets like API_KEY
"""

from .secrets import TEXT_API_KEY
from .gpu import KV_DTYPE, GPU_SM_ARCH, CHAT_GPU_FRAC, TOOL_GPU_FRAC
from .quantization import TRT_FP8_SM_ARCHS, SUPPORTED_ENGINES, VLLM_QUANTIZATIONS
from .deploy import CHAT_MODEL, TOOL_MODEL, DEPLOY_CHAT, DEPLOY_MODE, DEPLOY_TOOL, HF_REPO_PATTERN
from .models import (
    ALLOWED_TOOL_MODELS,
    ALLOWED_BASE_CHAT_MODELS,
    ALLOWED_BASE_MOE_CHAT_MODELS,
    ALLOWED_TRT_QUANT_CHAT_MODELS,
    ALLOWED_VLLM_QUANT_CHAT_MODELS,
)
from .engine import (
    INFERENCE_ENGINE,
    CHAT_QUANTIZATION,
    AWQ_METADATA_FILENAME,
    QUANT_CONFIG_FILENAMES,
    DEFAULT_MAX_BATCHED_TOKENS,
    UNSUPPORTED_QUANT_DTYPE_FIELDS,
)
from .chat import (
    DEFAULT_CHECK_SCREEN_PREFIX,
    CACHE_RESET_INTERVAL_SECONDS,
    CHAT_TEMPLATE_ENABLE_THINKING,
    DEFAULT_SCREEN_CHECKED_PREFIX,
    CACHE_RESET_MIN_SESSION_SECONDS,
)
from .tool import (
    TOOL_COMPILE,
    TOOL_MAX_LENGTH,
    TOOL_HISTORY_TOKENS,
    TOOL_LANGUAGE_FILTER,
    TOOL_DECISION_THRESHOLD,
    TOOL_MICROBATCH_MAX_SIZE,
    TOOL_MICROBATCH_MAX_DELAY_MS,
)
from .websocket import (
    WS_IDLE_TIMEOUT_S,
    WS_CLOSE_BUSY_CODE,
    WS_CLOSE_IDLE_CODE,
    WS_WATCHDOG_TICK_S,
    WS_CLOSE_IDLE_REASON,
    WS_CLOSE_UNAUTHORIZED_CODE,
    WS_CLOSE_CLIENT_REQUEST_CODE,
    WS_HANDSHAKE_ACQUIRE_TIMEOUT_S,
)
from .trt import (
    TRT_DTYPE,
    TRT_REPO_DIR,
    TRT_CALIB_SIZE,
    TRT_ENGINE_DIR,
    TRT_CALIB_SEQLEN,
    TRT_MAX_INPUT_LEN,
    TRT_AWQ_BLOCK_SIZE,
    TRT_CHECKPOINT_DIR,
    TRT_MAX_BATCH_SIZE,
    TRT_MAX_OUTPUT_LEN,
    TRT_KV_FREE_GPU_FRAC,
    TRT_RUNTIME_BATCH_SIZE,
)
from .limits import (
    CHAT_MAX_LEN,
    CHAT_MAX_OUT,
    CHAT_MIN_P_MAX,
    CHAT_MIN_P_MIN,
    CHAT_TOP_K_MAX,
    CHAT_TOP_K_MIN,
    CHAT_TOP_P_MAX,
    CHAT_TOP_P_MIN,
    STREAM_FLUSH_MS,
    EXACT_TOKEN_TRIM,
    HISTORY_MAX_TOKENS,
    PERSONALITY_MAX_LEN,
    USER_UTT_MAX_TOKENS,
    CHAT_TEMPERATURE_MAX,
    CHAT_TEMPERATURE_MIN,
    CHAT_PROMPT_MAX_TOKENS,
    TRIMMED_HISTORY_LENGTH,
    SCREEN_PREFIX_MAX_CHARS,
    WS_CANCEL_WINDOW_SECONDS,
    CHAT_PRESENCE_PENALTY_MAX,
    CHAT_PRESENCE_PENALTY_MIN,
    PROMPT_SANITIZE_MAX_CHARS,
    WS_MAX_CANCELS_PER_WINDOW,
    WS_MESSAGE_WINDOW_SECONDS,
    CHAT_FREQUENCY_PENALTY_MAX,
    CHAT_FREQUENCY_PENALTY_MIN,
    MAX_CONCURRENT_CONNECTIONS,
    WS_MAX_MESSAGES_PER_WINDOW,
    CHAT_REPETITION_PENALTY_MAX,
    CHAT_REPETITION_PENALTY_MIN,
)

__all__ = [
    # deploy
    "HF_REPO_PATTERN",
    "DEPLOY_MODE",
    "DEPLOY_CHAT",
    "DEPLOY_TOOL",
    "CHAT_MODEL",
    "TOOL_MODEL",
    # gpu
    "CHAT_GPU_FRAC",
    "TOOL_GPU_FRAC",
    "KV_DTYPE",
    "GPU_SM_ARCH",
    # engine
    "INFERENCE_ENGINE",
    "CHAT_QUANTIZATION",
    "SUPPORTED_ENGINES",
    "DEFAULT_MAX_BATCHED_TOKENS",
    "QUANT_CONFIG_FILENAMES",
    "AWQ_METADATA_FILENAME",
    "UNSUPPORTED_QUANT_DTYPE_FIELDS",
    # trt
    "TRT_ENGINE_DIR",
    "TRT_CHECKPOINT_DIR",
    "TRT_REPO_DIR",
    "TRT_MAX_BATCH_SIZE",
    "TRT_RUNTIME_BATCH_SIZE",
    "TRT_MAX_INPUT_LEN",
    "TRT_MAX_OUTPUT_LEN",
    "TRT_DTYPE",
    "TRT_KV_FREE_GPU_FRAC",
    "TRT_AWQ_BLOCK_SIZE",
    "TRT_CALIB_SIZE",
    "TRT_CALIB_SEQLEN",
    # chat
    "DEFAULT_CHECK_SCREEN_PREFIX",
    "DEFAULT_SCREEN_CHECKED_PREFIX",
    "CHAT_TEMPLATE_ENABLE_THINKING",
    "CACHE_RESET_INTERVAL_SECONDS",
    "CACHE_RESET_MIN_SESSION_SECONDS",
    # tool
    "TOOL_LANGUAGE_FILTER",
    "TOOL_DECISION_THRESHOLD",
    "TOOL_COMPILE",
    "TOOL_HISTORY_TOKENS",
    "TOOL_MAX_LENGTH",
    "TOOL_MICROBATCH_MAX_SIZE",
    "TOOL_MICROBATCH_MAX_DELAY_MS",
    # models
    "ALLOWED_BASE_CHAT_MODELS",
    "ALLOWED_BASE_MOE_CHAT_MODELS",
    "ALLOWED_VLLM_QUANT_CHAT_MODELS",
    "ALLOWED_TRT_QUANT_CHAT_MODELS",
    "ALLOWED_TOOL_MODELS",
    # quantization
    "TRT_FP8_SM_ARCHS",
    "VLLM_QUANTIZATIONS",
    # limits
    "CHAT_MAX_LEN",
    "CHAT_MAX_OUT",
    "PROMPT_SANITIZE_MAX_CHARS",
    "CHAT_TEMPERATURE_MIN",
    "CHAT_TEMPERATURE_MAX",
    "CHAT_TOP_P_MIN",
    "CHAT_TOP_P_MAX",
    "CHAT_TOP_K_MIN",
    "CHAT_TOP_K_MAX",
    "CHAT_MIN_P_MIN",
    "CHAT_MIN_P_MAX",
    "CHAT_REPETITION_PENALTY_MIN",
    "CHAT_REPETITION_PENALTY_MAX",
    "CHAT_PRESENCE_PENALTY_MIN",
    "CHAT_PRESENCE_PENALTY_MAX",
    "CHAT_FREQUENCY_PENALTY_MIN",
    "CHAT_FREQUENCY_PENALTY_MAX",
    "CHAT_PROMPT_MAX_TOKENS",
    "PERSONALITY_MAX_LEN",
    "STREAM_FLUSH_MS",
    "HISTORY_MAX_TOKENS",
    "TRIMMED_HISTORY_LENGTH",
    "USER_UTT_MAX_TOKENS",
    "WS_MESSAGE_WINDOW_SECONDS",
    "WS_MAX_MESSAGES_PER_WINDOW",
    "WS_CANCEL_WINDOW_SECONDS",
    "WS_MAX_CANCELS_PER_WINDOW",
    "EXACT_TOKEN_TRIM",
    "MAX_CONCURRENT_CONNECTIONS",
    "SCREEN_PREFIX_MAX_CHARS",
    # secrets
    "TEXT_API_KEY",
    # websocket
    "WS_IDLE_TIMEOUT_S",
    "WS_WATCHDOG_TICK_S",
    "WS_HANDSHAKE_ACQUIRE_TIMEOUT_S",
    "WS_CLOSE_UNAUTHORIZED_CODE",
    "WS_CLOSE_BUSY_CODE",
    "WS_CLOSE_IDLE_CODE",
    "WS_CLOSE_IDLE_REASON",
    "WS_CLOSE_CLIENT_REQUEST_CODE",
]
