"""Mark persona prompt definitions."""

from .detailed_blocks_d import (
    EPERSONA_LIKES_BLOCK,
    EBOY_VOICEPRINT_BLOCK,
    EPERSONA_QUIRKS_BLOCK,
    EPERSONA_TRAITS_BLOCK,
    EPERSONA_FEATURES_BLOCK,
    EPERSONA_MESSAGES_BLOCK,
    EPERSONA_BOUNDARIES_BLOCK,
    EPERSONA_HELPFULNESS_BLOCK,
    EPERSONA_SCREEN_PREP_BLOCK,
    EPERSONA_SEXUAL_TONE_BLOCK,
    EPERSONA_SCREEN_COMMENT_BLOCK,
)
from .detailed_dislikes import (
    MARK_EX_DISLIKES,
    MARK_KPOP_DISLIKES,
    MARK_WARM_DISLIKES,
    MARK_BOOMER_DISLIKES,
    MARK_DELULU_DISLIKES,
    MARK_FLIRTY_DISLIKES,
    MARK_FOODIE_DISLIKES,
    MARK_HONEST_DISLIKES,
    MARK_SAVAGE_DISLIKES,
    MARK_ZOOMER_DISLIKES,
    MARK_EPERSONA_DISLIKES,
    MARK_RELIGIOUS_DISLIKES,
    MARK_SPIRITUAL_DISLIKES,
    MARK_SHOPAHOLIC_DISLIKES,
)
from .detailed_blocks_b import (
    WARM_LIKES_BLOCK,
    WARM_QUIRKS_BLOCK,
    WARM_TRAITS_BLOCK,
    BOOMER_LIKES_BLOCK,
    FOODIE_LIKES_BLOCK,
    HONEST_LIKES_BLOCK,
    BOOMER_QUIRKS_BLOCK,
    BOOMER_TRAITS_BLOCK,
    FOODIE_QUIRKS_BLOCK,
    FOODIE_TRAITS_BLOCK,
    HONEST_QUIRKS_BLOCK,
    HONEST_TRAITS_BLOCK,
    WARM_FEATURES_BLOCK,
    WARM_MESSAGES_BLOCK,
    BOOMER_FEATURES_BLOCK,
    BOOMER_MESSAGES_BLOCK,
    FOODIE_FEATURES_BLOCK,
    FOODIE_MESSAGES_BLOCK,
    HONEST_FEATURES_BLOCK,
    HONEST_MESSAGES_BLOCK,
    WARM_BOUNDARIES_BLOCK,
    WARM_VOICEPRINT_BLOCK,
    WARM_HELPFULNESS_BLOCK,
    WARM_SCREEN_PREP_BLOCK,
    WARM_SEXUAL_TONE_BLOCK,
    BOOMER_BOUNDARIES_BLOCK,
    BOOMER_VOICEPRINT_BLOCK,
    FOODIE_BOUNDARIES_BLOCK,
    FOODIE_VOICEPRINT_BLOCK,
    HONEST_BOUNDARIES_BLOCK,
    HONEST_VOICEPRINT_BLOCK,
    BOOMER_HELPFULNESS_BLOCK,
    BOOMER_SCREEN_PREP_BLOCK,
    BOOMER_SEXUAL_TONE_BLOCK,
    FOODIE_HELPFULNESS_BLOCK,
    FOODIE_SCREEN_PREP_BLOCK,
    FOODIE_SEXUAL_TONE_BLOCK,
    HONEST_HELPFULNESS_BLOCK,
    HONEST_SCREEN_PREP_BLOCK,
    HONEST_SEXUAL_TONE_BLOCK,
    WARM_SCREEN_COMMENT_BLOCK,
    BOOMER_SCREEN_COMMENT_BLOCK,
    FOODIE_SCREEN_COMMENT_BLOCK,
    HONEST_SCREEN_COMMENT_BLOCK,
)
from .detailed_blocks_c import (
    EX_LIKES_BLOCK,
    EX_QUIRKS_BLOCK,
    EX_TRAITS_BLOCK,
    KPOP_LIKES_BLOCK,
    EX_FEATURES_BLOCK,
    EX_MESSAGES_BLOCK,
    KPOP_QUIRKS_BLOCK,
    KPOP_TRAITS_BLOCK,
    ZOOMER_LIKES_BLOCK,
    EX_BOUNDARIES_BLOCK,
    EX_VOICEPRINT_BLOCK,
    KPOP_FEATURES_BLOCK,
    KPOP_MESSAGES_BLOCK,
    ZOOMER_QUIRKS_BLOCK,
    ZOOMER_TRAITS_BLOCK,
    EX_HELPFULNESS_BLOCK,
    EX_SCREEN_PREP_BLOCK,
    EX_SEXUAL_TONE_BLOCK,
    KPOP_BOUNDARIES_BLOCK,
    KPOP_VOICEPRINT_BLOCK,
    ZOOMER_FEATURES_BLOCK,
    ZOOMER_MESSAGES_BLOCK,
    KPOP_HELPFULNESS_BLOCK,
    KPOP_SCREEN_PREP_BLOCK,
    KPOP_SEXUAL_TONE_BLOCK,
    SHOPAHOLIC_LIKES_BLOCK,
    EX_SCREEN_COMMENT_BLOCK,
    SHOPAHOLIC_QUIRKS_BLOCK,
    SHOPAHOLIC_TRAITS_BLOCK,
    ZOOMER_BOUNDARIES_BLOCK,
    ZOOMER_VOICEPRINT_BLOCK,
    ZOOMER_HELPFULNESS_BLOCK,
    ZOOMER_SCREEN_PREP_BLOCK,
    ZOOMER_SEXUAL_TONE_BLOCK,
    KPOP_SCREEN_COMMENT_BLOCK,
    SHOPAHOLIC_FEATURES_BLOCK,
    SHOPAHOLIC_MESSAGES_BLOCK,
    SHOPAHOLIC_BOUNDARIES_BLOCK,
    SHOPAHOLIC_VOICEPRINT_BLOCK,
    ZOOMER_SCREEN_COMMENT_BLOCK,
    SHOPAHOLIC_HELPFULNESS_BLOCK,
    SHOPAHOLIC_SCREEN_PREP_BLOCK,
    SHOPAHOLIC_SEXUAL_TONE_BLOCK,
    SHOPAHOLIC_SCREEN_COMMENT_BLOCK,
)
from .detailed_blocks_a import (
    AVOID_BLOCK,
    LANGUAGE_BLOCK,
    KNOWLEDGE_BLOCK,
    PUNCTUATION_BLOCK,
    DELULU_LIKES_BLOCK,
    FLIRTY_LIKES_BLOCK,
    MARK_PERSONA_BLOCK,
    SAVAGE_LIKES_BLOCK,
    USER_DETAILS_BLOCK,
    DELULU_QUIRKS_BLOCK,
    DELULU_TRAITS_BLOCK,
    DRAFTING_HELP_BLOCK,
    FLIRTY_QUIRKS_BLOCK,
    FLIRTY_TRAITS_BLOCK,
    SAVAGE_QUIRKS_BLOCK,
    SAVAGE_TRAITS_BLOCK,
    MESSAGE_LENGTH_BLOCK,
    DELULU_FEATURES_BLOCK,
    DELULU_MESSAGES_BLOCK,
    FLIRTY_FEATURES_BLOCK,
    FLIRTY_MESSAGES_BLOCK,
    RELIGIOUS_LIKES_BLOCK,
    SAVAGE_FEATURES_BLOCK,
    SAVAGE_MESSAGES_BLOCK,
    SPIRITUAL_LIKES_BLOCK,
    USER_ADDRESSING_BLOCK,
    RELIGIOUS_QUIRKS_BLOCK,
    RELIGIOUS_TRAITS_BLOCK,
    SPIRITUAL_QUIRKS_BLOCK,
    SPIRITUAL_TRAITS_BLOCK,
    DELULU_BOUNDARIES_BLOCK,
    DELULU_VOICEPRINT_BLOCK,
    FLIRTY_BOUNDARIES_BLOCK,
    FLIRTY_VOICEPRINT_BLOCK,
    SAVAGE_BOUNDARIES_BLOCK,
    SAVAGE_VOICEPRINT_BLOCK,
    DELULU_HELPFULNESS_BLOCK,
    DELULU_SCREEN_PREP_BLOCK,
    DELULU_SEXUAL_TONE_BLOCK,
    FLIRTY_HELPFULNESS_BLOCK,
    FLIRTY_SCREEN_PREP_BLOCK,
    FLIRTY_SEXUAL_TONE_BLOCK,
    RELIGIOUS_FEATURES_BLOCK,
    RELIGIOUS_MESSAGES_BLOCK,
    SAVAGE_HELPFULNESS_BLOCK,
    SAVAGE_SCREEN_PREP_BLOCK,
    SAVAGE_SEXUAL_TONE_BLOCK,
    SPIRITUAL_FEATURES_BLOCK,
    SPIRITUAL_MESSAGES_BLOCK,
    REALITY_CONSTRAINTS_BLOCK,
    RELIGIOUS_BOUNDARIES_BLOCK,
    RELIGIOUS_VOICEPRINT_BLOCK,
    SPIRITUAL_BOUNDARIES_BLOCK,
    SPIRITUAL_VOICEPRINT_BLOCK,
    DELULU_SCREEN_COMMENT_BLOCK,
    FLIRTY_SCREEN_COMMENT_BLOCK,
    RELIGIOUS_HELPFULNESS_BLOCK,
    RELIGIOUS_SCREEN_PREP_BLOCK,
    RELIGIOUS_SEXUAL_TONE_BLOCK,
    SAVAGE_SCREEN_COMMENT_BLOCK,
    SPIRITUAL_HELPFULNESS_BLOCK,
    SPIRITUAL_SCREEN_PREP_BLOCK,
    SPIRITUAL_SEXUAL_TONE_BLOCK,
    RELIGIOUS_SCREEN_COMMENT_BLOCK,
    SPIRITUAL_SCREEN_COMMENT_BLOCK,
)

MARK_FLIRTY = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{FLIRTY_VOICEPRINT_BLOCK}
{FLIRTY_SEXUAL_TONE_BLOCK}
{FLIRTY_TRAITS_BLOCK}
{FLIRTY_MESSAGES_BLOCK}
{FLIRTY_HELPFULNESS_BLOCK}
{FLIRTY_QUIRKS_BLOCK}
{FLIRTY_LIKES_BLOCK}
Dislikes:
{MARK_FLIRTY_DISLIKES}
{USER_DETAILS_BLOCK}
{FLIRTY_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{FLIRTY_SCREEN_PREP_BLOCK}
{FLIRTY_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{FLIRTY_BOUNDARIES_BLOCK}
"""

MARK_SAVAGE = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{SAVAGE_VOICEPRINT_BLOCK}
{SAVAGE_SEXUAL_TONE_BLOCK}
{SAVAGE_TRAITS_BLOCK}
{SAVAGE_MESSAGES_BLOCK}
{SAVAGE_HELPFULNESS_BLOCK}
{SAVAGE_QUIRKS_BLOCK}
{SAVAGE_LIKES_BLOCK}
Dislikes:
{MARK_SAVAGE_DISLIKES}
{USER_DETAILS_BLOCK}
{SAVAGE_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{SAVAGE_SCREEN_PREP_BLOCK}
{SAVAGE_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{SAVAGE_BOUNDARIES_BLOCK}
"""

MARK_RELIGIOUS = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{RELIGIOUS_VOICEPRINT_BLOCK}
{RELIGIOUS_SEXUAL_TONE_BLOCK}
{RELIGIOUS_TRAITS_BLOCK}
{RELIGIOUS_MESSAGES_BLOCK}
{RELIGIOUS_HELPFULNESS_BLOCK}
{RELIGIOUS_QUIRKS_BLOCK}
{RELIGIOUS_LIKES_BLOCK}
Dislikes:
{MARK_RELIGIOUS_DISLIKES}
{USER_DETAILS_BLOCK}
{RELIGIOUS_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{RELIGIOUS_SCREEN_PREP_BLOCK}
{RELIGIOUS_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{RELIGIOUS_BOUNDARIES_BLOCK}
"""

MARK_DELULU = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{DELULU_VOICEPRINT_BLOCK}
{DELULU_SEXUAL_TONE_BLOCK}
{DELULU_TRAITS_BLOCK}
{DELULU_MESSAGES_BLOCK}
{DELULU_HELPFULNESS_BLOCK}
{DELULU_QUIRKS_BLOCK}
{DELULU_LIKES_BLOCK}
Dislikes:
{MARK_DELULU_DISLIKES}
{USER_DETAILS_BLOCK}
{DELULU_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{DELULU_SCREEN_PREP_BLOCK}
{DELULU_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{DELULU_BOUNDARIES_BLOCK}
"""

MARK_SPIRITUAL = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{SPIRITUAL_VOICEPRINT_BLOCK}
{SPIRITUAL_SEXUAL_TONE_BLOCK}
{SPIRITUAL_TRAITS_BLOCK}
{SPIRITUAL_MESSAGES_BLOCK}
{SPIRITUAL_HELPFULNESS_BLOCK}
{SPIRITUAL_QUIRKS_BLOCK}
{SPIRITUAL_LIKES_BLOCK}
Dislikes:
{MARK_SPIRITUAL_DISLIKES}
{USER_DETAILS_BLOCK}
{SPIRITUAL_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{SPIRITUAL_SCREEN_PREP_BLOCK}
{SPIRITUAL_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{SPIRITUAL_BOUNDARIES_BLOCK}
"""

MARK_FOODIE = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{FOODIE_VOICEPRINT_BLOCK}
{FOODIE_SEXUAL_TONE_BLOCK}
{FOODIE_TRAITS_BLOCK}
{FOODIE_MESSAGES_BLOCK}
{FOODIE_HELPFULNESS_BLOCK}
{FOODIE_QUIRKS_BLOCK}
{FOODIE_LIKES_BLOCK}
Dislikes:
{MARK_FOODIE_DISLIKES}
{USER_DETAILS_BLOCK}
{FOODIE_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{FOODIE_SCREEN_PREP_BLOCK}
{FOODIE_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{FOODIE_BOUNDARIES_BLOCK}
"""

MARK_WARM = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{WARM_VOICEPRINT_BLOCK}
{WARM_SEXUAL_TONE_BLOCK}
{WARM_TRAITS_BLOCK}
{WARM_MESSAGES_BLOCK}
{WARM_HELPFULNESS_BLOCK}
{WARM_QUIRKS_BLOCK}
{WARM_LIKES_BLOCK}
Dislikes:
{MARK_WARM_DISLIKES}
{USER_DETAILS_BLOCK}
{WARM_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{WARM_SCREEN_PREP_BLOCK}
{WARM_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{WARM_BOUNDARIES_BLOCK}
"""

MARK_HONEST = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{HONEST_VOICEPRINT_BLOCK}
{HONEST_SEXUAL_TONE_BLOCK}
{HONEST_TRAITS_BLOCK}
{HONEST_MESSAGES_BLOCK}
{HONEST_HELPFULNESS_BLOCK}
{HONEST_QUIRKS_BLOCK}
{HONEST_LIKES_BLOCK}
Dislikes:
{MARK_HONEST_DISLIKES}
{USER_DETAILS_BLOCK}
{HONEST_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{HONEST_SCREEN_PREP_BLOCK}
{HONEST_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{HONEST_BOUNDARIES_BLOCK}
"""

MARK_BOOMER = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{BOOMER_VOICEPRINT_BLOCK}
{BOOMER_SEXUAL_TONE_BLOCK}
{BOOMER_TRAITS_BLOCK}
{BOOMER_MESSAGES_BLOCK}
{BOOMER_HELPFULNESS_BLOCK}
{BOOMER_QUIRKS_BLOCK}
{BOOMER_LIKES_BLOCK}
Dislikes:
{MARK_BOOMER_DISLIKES}
{USER_DETAILS_BLOCK}
{BOOMER_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{BOOMER_SCREEN_PREP_BLOCK}
{BOOMER_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{BOOMER_BOUNDARIES_BLOCK}
"""

MARK_ZOOMER = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{ZOOMER_VOICEPRINT_BLOCK}
{ZOOMER_SEXUAL_TONE_BLOCK}
{ZOOMER_TRAITS_BLOCK}
{ZOOMER_MESSAGES_BLOCK}
{ZOOMER_HELPFULNESS_BLOCK}
{ZOOMER_QUIRKS_BLOCK}
{ZOOMER_LIKES_BLOCK}
Dislikes:
{MARK_ZOOMER_DISLIKES}
{USER_DETAILS_BLOCK}
{ZOOMER_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{ZOOMER_SCREEN_PREP_BLOCK}
{ZOOMER_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{ZOOMER_BOUNDARIES_BLOCK}
"""

MARK_EX = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{EX_VOICEPRINT_BLOCK}
{EX_SEXUAL_TONE_BLOCK}
{EX_TRAITS_BLOCK}
{EX_MESSAGES_BLOCK}
{EX_HELPFULNESS_BLOCK}
{EX_QUIRKS_BLOCK}
{EX_LIKES_BLOCK}
Dislikes:
{MARK_EX_DISLIKES}
{USER_DETAILS_BLOCK}
{EX_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{EX_SCREEN_PREP_BLOCK}
{EX_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{EX_BOUNDARIES_BLOCK}
"""

MARK_KPOP = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{KPOP_VOICEPRINT_BLOCK}
{KPOP_SEXUAL_TONE_BLOCK}
{KPOP_TRAITS_BLOCK}
{KPOP_MESSAGES_BLOCK}
{KPOP_HELPFULNESS_BLOCK}
{KPOP_QUIRKS_BLOCK}
{KPOP_LIKES_BLOCK}
Dislikes:
{MARK_KPOP_DISLIKES}
{USER_DETAILS_BLOCK}
{KPOP_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{KPOP_SCREEN_PREP_BLOCK}
{KPOP_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{KPOP_BOUNDARIES_BLOCK}
"""

MARK_SHOPAHOLIC = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{SHOPAHOLIC_VOICEPRINT_BLOCK}
{SHOPAHOLIC_SEXUAL_TONE_BLOCK}
{SHOPAHOLIC_TRAITS_BLOCK}
{SHOPAHOLIC_MESSAGES_BLOCK}
{SHOPAHOLIC_HELPFULNESS_BLOCK}
{SHOPAHOLIC_QUIRKS_BLOCK}
{SHOPAHOLIC_LIKES_BLOCK}
Dislikes:
{MARK_SHOPAHOLIC_DISLIKES}
{USER_DETAILS_BLOCK}
{SHOPAHOLIC_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{SHOPAHOLIC_SCREEN_PREP_BLOCK}
{SHOPAHOLIC_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{SHOPAHOLIC_BOUNDARIES_BLOCK}
"""

MARK_EPERSONA = f"""{MESSAGE_LENGTH_BLOCK}
{MARK_PERSONA_BLOCK}
{EBOY_VOICEPRINT_BLOCK}
{EPERSONA_SEXUAL_TONE_BLOCK}
{EPERSONA_TRAITS_BLOCK}
{EPERSONA_MESSAGES_BLOCK}
{EPERSONA_HELPFULNESS_BLOCK}
{EPERSONA_QUIRKS_BLOCK}
{EPERSONA_LIKES_BLOCK}
Dislikes:
{MARK_EPERSONA_DISLIKES}
{USER_DETAILS_BLOCK}
{EPERSONA_FEATURES_BLOCK}
{REALITY_CONSTRAINTS_BLOCK}
{KNOWLEDGE_BLOCK}
User's Local Time and Date:
4:20PM, December 13th 2025, late afternoon.
{EPERSONA_SCREEN_PREP_BLOCK}
{EPERSONA_SCREEN_COMMENT_BLOCK}
{DRAFTING_HELP_BLOCK}
{USER_ADDRESSING_BLOCK}
{LANGUAGE_BLOCK}
{PUNCTUATION_BLOCK}
{AVOID_BLOCK}
{EPERSONA_BOUNDARIES_BLOCK}
"""

# =============================================================================

__all__ = [
    "MARK_FLIRTY",
    "MARK_SAVAGE",
    "MARK_RELIGIOUS",
    "MARK_DELULU",
    "MARK_SPIRITUAL",
    "MARK_FOODIE",
    "MARK_WARM",
    "MARK_HONEST",
    "MARK_BOOMER",
    "MARK_ZOOMER",
    "MARK_EX",
    "MARK_KPOP",
    "MARK_SHOPAHOLIC",
    "MARK_EPERSONA",
]
