"""Environment variable names referenced in tests."""

ORPHEUS_API_KEY_ENV = "ORPHEUS_API_KEY"
TTS_VOICE_ENV = "TTS_VOICE"
SERVER_URL_ENV = "YAP_TTS_SERVER"
CLOUD_TCP_HOST_ENV = "CLOUD_TCP_HOST"
CLOUD_TCP_PORT_ENV = "CLOUD_TCP_PORT"
WS_MAX_CONNECTIONS_ENV = "WS_MAX_CONNECTIONS"
SILENCE_PRESPEECH_PAD_MS_ENV = "SILENCE_PRESPEECH_PAD_MS"
