#!/usr/bin/env bash
# =============================================================================
# Restart Guard - Config Snapshot Decisions
# =============================================================================
# Snapshot comparisons and stop strategy selection.

# Compare requested deployment parameters with the last snapshot.
# Returns 0 when everything matches and 1 otherwise.
configs_match() {
  local desired_deploy="$1"
  local desired_chat="$2"
  local desired_tool="$3"
  local desired_chat_quant="$4"
  local desired_engine="${5:-}"
  local root_dir="${6:-${ROOT_DIR:-}}"

  local last_deploy last_chat last_tool last_chat_quant last_engine
  last_deploy="$(read_last_config_value "DEPLOY_MODE" "${root_dir}")"
  last_chat="$(read_last_config_value "CHAT_MODEL" "${root_dir}")"
  last_tool="$(read_last_config_value "TOOL_MODEL" "${root_dir}")"
  last_chat_quant="$(read_last_config_value "CHAT_QUANTIZATION" "${root_dir}")"
  last_engine="$(read_last_config_value "INFERENCE_ENGINE" "${root_dir}")"

  if [ -z "${last_deploy:-}" ]; then
    return 1
  fi

  # Tool-only deployments are engine-agnostic.
  if [ "${desired_deploy:-}" = "${CFG_DEPLOY_MODE_TOOL}" ]; then
    if [ "${desired_deploy:-}" = "${last_deploy:-}" ] &&
      [ "${desired_tool:-}" = "${last_tool:-}" ]; then
      return 0
    fi
    return 1
  fi

  desired_engine="$(echo "${desired_engine:-${CFG_DEFAULT_ENGINE}}" | tr '[:upper:]' '[:lower:]')"
  last_engine="$(echo "${last_engine:-}" | tr '[:upper:]' '[:lower:]')"

  if [ "${desired_deploy:-}" = "${last_deploy:-}" ] &&
    [ "${desired_chat:-}" = "${last_chat:-}" ] &&
    [ "${desired_tool:-}" = "${last_tool:-}" ] &&
    [ "${desired_chat_quant:-}" = "${last_chat_quant:-}" ] &&
    [ "${desired_engine:-}" = "${last_engine:-}" ]; then
    return 0
  fi
  return 1
}

# Decide whether to stop a running server and whether caches can be preserved.
stop_server_if_needed() {
  local script_dir="$1"
  shift
  local root_dir="$1"
  shift
  local desired_deploy="$1"
  shift
  local desired_chat="$1"
  shift
  local desired_tool="$1"
  shift
  local desired_chat_quant="$1"
  shift
  local desired_engine="${1:-}"

  local switch_result=0
  handle_engine_switch "${script_dir}" "${root_dir}" "${desired_engine}" "${desired_deploy}" || switch_result=$?

  case "${switch_result}" in
    0)
      return 0
      ;;
    2)
      return 1
      ;;
  esac

  local running_pid
  if ! running_pid="$(get_running_server_pid "${root_dir}")"; then
    return 0
  fi

  log_blank
  log_warn "[server] ⚠ Server already running (PID=${running_pid}). Evaluating restart strategy..."
  if configs_match \
    "${desired_deploy}" \
    "${desired_chat}" \
    "${desired_tool}" \
    "${desired_chat_quant}" \
    "${desired_engine}" \
    "${root_dir}"; then
    log_info "[server] Existing server matches requested config; stopping without clearing caches."
    if ! FULL_CLEANUP=0 bash "${script_dir}/stop.sh"; then
      log_err "[server] ✗ stop.sh failed during light stop"
      return 1
    fi
  else
    log_info "[server] Requested configuration differs; performing full reset before redeploy."
    if ! FULL_CLEANUP=1 bash "${script_dir}/stop.sh"; then
      log_err "[server] ✗ stop.sh failed during full reset"
      return 1
    fi
  fi
}

# Persist last-known-good deployment config for future comparisons.
write_snapshot() {
  local root_dir="${1:-${ROOT_DIR:-}}"
  local run_dir="${root_dir}/${CFG_RUNTIME_RUN_DIR}"
  local env_file="${root_dir}/${CFG_RUNTIME_LAST_CONFIG_FILE}"
  local deploy_mode="${DEPLOY_MODE:-}"
  mkdir -p "${run_dir}"
  {
    echo "# Autogenerated by write_snapshot"
    if [ "${deploy_mode}" != "${CFG_DEPLOY_MODE_TOOL}" ]; then
      echo "INFERENCE_ENGINE=${INFERENCE_ENGINE:-${CFG_DEFAULT_ENGINE}}"
    fi
    echo "DEPLOY_MODE=${DEPLOY_MODE:-}"
    echo "CHAT_MODEL=${CHAT_MODEL:-}"
    echo "TOOL_MODEL=${TOOL_MODEL:-}"
    echo "CHAT_QUANTIZATION=${CHAT_QUANTIZATION:-}"
    echo "KV_DTYPE=${KV_DTYPE:-}"
    echo "GPU_SM_ARCH=${GPU_SM_ARCH:-}"
  } >"${env_file}" 2>/dev/null || true
}
